[package]
name = "gaimode"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30.1", features = ["process"] }
gaiproto = { path = "../gaiproto" }
clap = { version = "4.5.53", features = ["derive"] }
anyhow = "1.0.100"
